[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.12",
    "pybind11",
    "numpy",
    "mpi4py"
]
build-backend = "setuptools.build_meta"

[tool.ruff.lint]
select = ["F", "E", "W", "I001"]
ignore-init-module-imports = true

[tool.ruff]
line-length = 120
