name: Regression Tests

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted]
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: build
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14
          mkdir build && cd build && cmake -DOPENSN_WITH_PYTHON_MODULE=ON .. && make -j && cd ..
      - name: test
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14
          test/run_tests -d test/python -j 32 -v 1 -w 3
      - name: test tutorials
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14
          export PYTHONPATH=$PWD/build
          test/run_tests -d doc/source/tutorials -j 32 -v 1 -w 3 --engine=jupyter
      - name: test unit
        shell: bash
        run: |
          module load python3/3.12.3 opensn/gcc/14
          build/test/opensn-unit
  cuda:
    runs-on: [self-hosted, cuda]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: build
        shell: bash
        run: |
          module load cuda/12.9 python3/3.12.3 opensn/gcc/14
          mkdir build && cd build && cmake -DOPENSN_WITH_CUDA=ON -DCMAKE_CUDA_ARCHITECTURES=89 -DOPENSN_WITH_PYTHON_MODULE=ON .. && make -j && cd ..
      - name: test
        shell: bash
        run: |
          module load cuda/12.9 python3/3.12.3 opensn/gcc/14
          test/run_tests --gpu -d test/python -j 32 -v 1
  hip:
    runs-on: [self-hosted, cuda]
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: build
        shell: bash
        run: |
          module load cuda/12.9 python3/3.12.3 rocm/7.1.1 opensn/clang/19
          export HIP_PLATFORM=nvidia
          export HIP_COMPILER=nvcc
          mkdir build && cd build && cmake -DOPENSN_WITH_HIP=ON -DCMAKE_HIP_ARCHITECTURES=89 -DOPENSN_WITH_PYTHON_MODULE=ON .. && make -j && cd ..
      - name: test
        shell: bash
        run: |
          module load cuda/12.9 python3/3.12.3 rocm/7.1.1 opensn/clang/19
          test/run_tests --gpu -d test/python -j 32 -v 1
